# Attempting to use Multiple Regression

In [1]:
import sklearn
from sklearn.linear_model import LinearRegression
import pandas

In [2]:
dataset = pandas.read_csv("processed.cleveland.data")
dataset

,63.0,1.0,1.0.1,145.0,233.0,1.0.2,2.0,150.0,0.0,2.3,3.0,0.0.1,6.0,0
0,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
1,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
2,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
3,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
4,56.0,1.0,2.0,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
298,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
299,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
300,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
301,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0

In [3]:
model = LinearRegression()
dataset = dataset.replace('?', None)
dataset.dropna(inplace=True)

xs = dataset.iloc[:, 0:13]
ys = dataset.iloc[:,-1]

In [17]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

training_x, testing_x, training_y, testing_y = train_test_split(xs, ys, test_size=0.2)

model.fit(training_x, training_y)

predictions = model.predict(testing_x)
rounded = [round(pred) for pred in predictions]

print(f"R2 Score: {r2_score(testing_y, predictions)}")
print(f"Rounded R2 Score: {r2_score(testing_y, rounded)}")

R2 Score: 0.6024459994521323
Rounded R2 Score: 0.5683453237410073

## Pretty Bad!

The R2 scores over 10 trials ranged from slightly above 0.6 to below 0.33. This is a wide range of low scores, proving that this model does not do a good job.